


const list: string[] = [
    'gorilla',
    'wallaby',
    'orangutan',
    'zebra',
    'cantaloupe',
    'pizza',
    'eggplant',
    'asteroid',
    'jupiter',
    'jungle-gym',
    'alligator',
    'crocodile',
    'tyrannosaurus-rex',
    'brontosaurus',
    'developer',
    'x-ray',
    'xylophone',
    'quiche',
    'quagmire',
    'parquet',
    'requisite',
    'chimpanzee',
    'locomotive',
    'janitor',
    'lizard',
    'chihuahua',
    'labrador',
    'tabby-cat',
    'porpoise',
    'squid',
    'tentacle',
    'opossum',
    'racoon',
    'anemone',
    'quisling',
    'raspberry',
    'turmeric',
    'ginger',
    'quinine',
    'mosquito',
    'ukulele',
    'camel',
    'forest',
    'monkey',
    'azalea',
    'zigzag',
    'lacquer',
    'quantum',
    'venus'
]

export default list
